apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment-3
  namespace: lpintofsgrp-dev
  labels:
    app: {{ .Values.labels.app }}
    areanegocio: tecnologia
spec:
  replicas: {{ .Values.replicas.minReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: contenedor-principal
          image: "{{ .Values.containers.image }}:build-{{ .Values.containers.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containers.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.cpu }}
              memory: {{ .Values.resources.memory }}
            limits:
              cpu: {{ .Values.resources.limit_cpu }}
              memory: {{ .Values.resources.limit_memory }}
