name: CI-DockerBuild

on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub (for Docker CLI)
        uses: docker/login-action@v3
        with:
          registry: registry-1.docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Log in to Docker Hub (for Helm OCI)
        run: |
          helm registry login registry-1.docker.io \
            --username ${{ secrets.DOCKER_USERNAME }} \
            --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Package and Push Helm Chart
        run: |
          sed -i "s|{{ version }}|${{ github.run_number }}|g" ./mi-chart/Chart.yaml
          cat ./mi-chart/Chart.yaml
          helm package ./mi-chart
          helm push ./mi-chart-${{ github.run_number }}.tgz oci://registry-1.docker.io/lpintofsgrp
